server:
  port: 8020
spring:
  datasource:
    username: root
    password: India@123
    url: jdbc:mysql://localhost:3306/stock-dev
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
info:
  author: Bhaskar
